fruits = ["apple", "banana", "cherry"]
numbers = [1, 2, 3, 4]
mixed_list = [1, "apple", 3.14, True]
print(fruits)  # Output: ['apple', 'banana', 'cherry']
print(numbers)  # Output: [1, 2, 3, 4]
print(mixed_list)  # Output: [1, 'apple', 3.14, True]